sudo: required
dist: xenial
language: cpp
cache:
  - apt
  - directories:

compiler:
  - g++

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE"
  matrix:
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 DOWNLOAD_QT=FALSE

    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.13 QT_VERSION=5.13.1 DOWNLOAD_QT=TRUE STATIC=ON

    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 ANDROID_API=android-24 DOWNLOAD_QT=TRUE
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE STATIC=ON

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v0.1.3"

install:
  - cd ${SOURCE_DIR}
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh > /dev/null
#  - |
#    if [ "$BUILD_TARGERT"="unix" -a -z "$RABBIT_ARCH" ]; then
#        source /opt/qt511/bin/qt511-env.sh
#    fi

before_script:
  - cd ${SOURCE_DIR}

script:
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

#after_script:
#  - "xpra stop :99"

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

#deploy:
#  provider: releases
#  api_key:
#    secure: Ay7qSOP76v3aEYH8MDmVcgpB5zM6X8h5+0ewcYeEzpzhPNq+W7Wsny8TAv1ZUrZraJnpeh46z1hqlE+Be3sm4/MRGK0XrEdv681zexvVnAcQwfU79TuMCxpRMX7Yh1OhDKd0PfPo3NHGv5tJbLAJCy32f7lCMH8K3Dgiqw2zb5OOqrHHXJYjtntX4FhlEDu9r3X4i/jJsPsiXQBPjb5697pj/xxg4K1w3HC/X9OVDoPAyiEJWHWmcvdNDehq7hQNT/AYGlNNnbs7M8zrLgrUjQYxjumtn1pDbpkVYqXVFnB3rjjlqk4WFuMrq3lEg83OmNWdpX4xvA+lo2Nid8VpFMSbbgO3BPe4Sqq5uWDMbvhH7Tnpr+y31OllFOsEU2uu6GbtSFvsllNDrJbgETsL/eIPdoIHQqcV0nZNPylEd+KHh0fFJ+i/etGwZGigsXgGKLBDbnQ6b2BndbPCafEbF3hotEjNySrKxnmSCTQQ++5OtkjhhLMeYyIpEI1+7VMXynH0fuSgO8z5nKi1z4y0qS5Vm+VPSjuKgcdcpXEOwomL4jarF/nQATv9b2M9o7yzW0awAMtBqxX3WLO64P1q8wfAOYo/oYZbd6ag30WGxmsHIgC9///tLY+lg4xfN+J6u9RB5VQuXt8Q7yWiSkMGSqQF1FS8t2LOV1uV9JqBF5w=
#  file: $TRAVIS_BUILD_DIR/../lunarcalendar_*_amd64.deb
#  skip_cleanup: true
#  draft: true
#  on:
#    tags: true
#    condition: "$BUILD_TARGERT=unix && $QT_VERSION=5.12.4"
