sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE" 

  matrix:
     - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2
     - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7
     - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3

     #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2
     #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.8 QT_VERSION=5.9.7
     #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir ${SOURCE_DIR}/Tools
  
install:
  - bash ci/build-install-tools.sh #> /dev/null

before_script:
  - cd ${SOURCE_DIR}

script: 
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

#deploy:
#  provider: releases
#  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
#  file: 
#    - ./build_android/android-build/bin/QtApp-debug.apk
#  skip_cleanup: true
#  on:
#    condition: $TRAVIS_OS_NAME = android
#    repo: KangLin/SerialPortAssistant
#    tags: true
