sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE" 

  matrix:
     - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2
     - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.10 QT_VERSION=5.10.1 GENERATORS="Unix Makefiles" STATIC=ON
     - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7 
     - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3

     - BUILD_TARGERT="android" BUILD_ARCH="armv7" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2 ANDROID_API=android-24
     - BUILD_TARGERT="android" BUILD_ARCH="armv7" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7 ANDROID_API=android-24
     - BUILD_TARGERT="android" BUILD_ARCH="armv7" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3 ANDROID_API=android-18

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir ${SOURCE_DIR}/Tools
  
install:
  - cd ${SOURCE_DIR}
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh > /dev/null

before_script:
  - cd ${SOURCE_DIR}

script: 
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  #https://github.com/settings/tokens
  api_key: 53dda7f59e469b59646f395f2907a78cbed83bc8
  file: 
    - $TRAVIS_BUILD_DIR/../lunarcalendar_*_amd64.deb
  skip_cleanup: true
  draft: true
  on:
    condition: $BUILD_TARGERT=unix
    repo: KangLin/LunarCalendar
    #tags: true
