#TODO: Change version
version: 'v0.0.3.{build}'

environment:
  matrix: 
  ##### msvc 2013 ########
  - BUILD_TARGERT: windows_msvc
    #GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013
    AUTOBUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013 Win64"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013_64
    AUTOBUILD_ARCH: x64

  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015_64
    AUTOBUILD_ARCH: x64
  
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.6\msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.6\msvc2015_64
    AUTOBUILD_ARCH: x64

  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #GENERATORS: "Visual Studio 14 2015"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017
    AUTOBUILD_ARCH: x86

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017_64
    AUTOBUILD_ARCH: x64
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.10\msvc2017_64
    AUTOBUILD_ARCH: x64
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.9\msvc2017_64
    AUTOBUILD_ARCH: x64
  
  ##### mingw ########
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 492_32
    QT_ROOT: C:\Qt\5.6\mingw49_32
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530_32
    QT_ROOT: C:\Qt\5.10\mingw53_32
    AUTOBUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 730_64
    QT_ROOT: C:\Qt\5.12\mingw73_64
    AUTOBUILD_ARCH: x64

matrix:
  fast_finish: false

init:
  - set BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - set varch=%AUTOBUILD_ARCH%
  - if "%AUTOBUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - if NOT "%QT_ROOT%" == "NO" for /f "delims=" %%i in ('%QT_ROOT%/bin/qmake -query QT_VERSION') do (set QT_VERSION=%%i) 
  - echo QT_ROOT=%QT_ROOT%
  - echo QT_VERSION=%QT_VERSION%
  - del C:\msys64\usr\bin\link.exe
  
install:
  - C:\msys64\autorebase.bat
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build.sh

artifacts:
  - path: build_${BUILD_TARGERT}/Tasks-Setup-*.exe
    name: Tasks_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    type: zip
    
  - path: build_${BUILD_TARGERT}/update_windows.xml

test: off

#See:https://www.appveyor.com/docs/deployment/github/
deploy:
  - provider: GitHub
    #release: Tasksv$(appveyor_build_version)
    description: 'Release Tasks $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: Tasks$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 12
      QT_VERSION: 5.6.3
      AUTOBUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
