Document: lunarcalendar
Title: Debian lunarcalendar Manual
Author: <insert document author here>
Abstract: This manual describes what lunarcalendar is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lunarcalendar/lunarcalendar.sgml.gz

Format: postscript
Files: /usr/share/doc/lunarcalendar/lunarcalendar.ps.gz

Format: text
Files: /usr/share/doc/lunarcalendar/lunarcalendar.text.gz

Format: HTML
Index: /usr/share/doc/lunarcalendar/html/index.html
Files: /usr/share/doc/lunarcalendar/html/*.html
