# 作者：康林 <kl222@126.com>

name: build

env:
  artifact_path: artifact_path
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LunarCalendar_VERSION: v0.2.7

on:
  push:

jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  android:
    uses: ./.github/workflows/android.yml

  deploy:
    #if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [ubuntu, msvc, mingw, macos, android]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download ubuntu
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ubuntu.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download msvc
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.msvc.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download mingw
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.mingw.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download macos
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.macos.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download android
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.android.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Make Notes.md file
        run: |
          cd ${{ env.artifact_path }}
          echo "[:cn: 修改日志](https://github.com/KangLin/LunarCalendar/blob/${{env.LunarCalendar_VERSION}}/ChangeLog.md)" > ${{github.workspace}}/Notes.md
          echo "" >> ${{github.workspace}}/Notes.md
          echo "文件签名:" >> ${{github.workspace}}/Notes.md
          for file in *
          do
              #echo $file
              if [ -f $file ] && [ "${file##*.}" != "xml" ]; then
                  #echo "md5sum $file"
                  md5sum $file > $file.md5sum
                  cat $file.md5sum >> ${{github.workspace}}/Notes.md
              fi
          done

      - name: Upload To Github Release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file ${{github.workspace}}/Notes.md
          gh release upload ${{ github.ref_name }} ${{github.workspace}}/${{ env.artifact_path }}/* ${{github.workspace}}/Notes.md
